version: '2'
services:
  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"     
    environment:
      - SERVICE_MODE=${SERVICE_MODE}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_USER=${LASTFM_USER}
    env_file:
      - .env
    volumes:
      - ./public:/app/public   
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "${PORTAINER_PORT:-9000}:9000"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data: