version: '2'
services:
  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"     
    environment:
      - SERVICE_MODE=${SERVICE_MODE}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_USER=${LASTFM_USER}  
      - LAT=${LAT} 
      - LON=${LON} 
    restart: always

